# Generated by Django 4.1.7 on 2023-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('no_of_refugee', models.IntegerField(default=0)),
                ('casualities', models.IntegerField(default=0)),
                ('availability_status_of_food', models.CharField(max_length=10)),
                ('availability_status_of_resources', models.CharField(max_length=10)),
                ('medical_needs', models.CharField(blank=True, max_length=1000, null=True)),
                ('special_needs', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('dob', models.DateField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
