# Generated by Django 4.1.7 on 2023-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='dob',
            field=models.DateField(),
        ),
    ]
