# Generated by Django 4.1.7 on 2023-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_refugee_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Guidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_disaster', models.CharField(max_length=1000)),
                ('during_disatser', models.CharField(max_length=1000)),
                ('after_disaster', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='camp',
            name='availability_status_of_food',
            field=models.CharField(choices=[('Low', 'low'), ('Moderate', 'moderate'), ('High', 'high')], max_length=10),
        ),
        migrations.AlterField(
            model_name='camp',
            name='availability_status_of_resources',
            field=models.CharField(choices=[('Low', 'low'), ('Moderate', 'moderate'), ('High', 'high')], max_length=10),
        ),
    ]
