# Generated by Django 4.1.7 on 2023-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_identification_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Western', 'western'), ('Central', 'central'), ('Southern', 'southern'), ('Northern', 'northern'), ('Eastern', 'eastern'), ('North-_Western', 'north-western'), ('North-Eastern', 'north-eastern'), ('Uva', 'uva'), ('Sabaragamuwa', 'sabaragamuwa')], max_length=100)),
            ],
        ),
    ]
