# Generated by Django 4.1.7 on 2023-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(choices=[('Western', 'western'), ('Central', 'central'), ('Southern', 'southern'), ('Northern', 'northern'), ('Eastern', 'eastern'), ('North-Western', 'north-western'), ('North-Eastern', 'north-eastern'), ('Uva', 'uva'), ('Sabaragamuwa', 'sabaragamuwa')], max_length=100),
        ),
    ]
