# Generated by Django 4.1.7 on 2023-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_province_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
