# Generated by Django 4.2 on 2023-08-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='disasters',
            field=models.ManyToManyField(to='app.disaster'),
        ),
        migrations.CreateModel(
            name='LocationDisaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disaster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
    ]
