# Generated by Django 4.2 on 2023-08-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_location_disasters_locationdisaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisaster',
            old_name='Disaster',
            new_name='disaster',
        ),
        migrations.AddField(
            model_name='village',
            name='disasters',
            field=models.ManyToManyField(to='app.disaster'),
        ),
        migrations.CreateModel(
            name='VillageDisaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disaster')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
    ]
