# Generated by Django 4.2 on 2023-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_disaster_locationdisaster_disaster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'permissions': [('print_camp', 'Can print camp')]},
        ),
        migrations.AlterModelOptions(
            name='locationdisaster',
            options={'permissions': [('print_locationdisaster', 'Can print locationdisaster')]},
        ),
        migrations.AlterModelOptions(
            name='refugee',
            options={'permissions': [('print_refugee', 'Can print refugee')]},
        ),
        migrations.AlterModelOptions(
            name='villagedisaster',
            options={'permissions': [('print_villagedisaster', 'Can print villagedisaster')]},
        ),
    ]
