# Generated by Django 4.2 on 2023-09-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
