# Generated by Django 4.2 on 2023-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_refugee_age_alter_refugee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='age',
            field=models.IntegerField(verbose_name=22),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='dob',
            field=models.DateField(verbose_name='2002/09/01'),
        ),
    ]
