# Generated by Django 4.1.7 on 2023-09-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_refugee_age_alter_refugee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='disasters',
        ),
    ]
