# Generated by Django 4.2.6 on 2024-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camp',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
