# Generated by Django 4.2.6 on 2024-01-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refugee',
            options={'permissions': [('generate_camp_pdf', 'Can print refugee')]},
        ),
    ]
